In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("copy-of-2025-enhanced-statewide-summary.csv")

In [4]:
data.head()

,District\nNumber,District,Campus\nNumber,Campus,Region,County,School\nType,Grades\nServed,Alternative\nEducation\nAccountability,Charter,...,Distinction\nProgress,Distinction\nClosing the Gaps,Distinction\nPostsecondary\nReadiness,US Congress\nDistrict,US Congress\nElection District,TX House\nDistrict,TX House\nElection District,TX Senate\nDistrict,TX Senate\nElection District,Campus Enrollment\nType
0,1902,CAYUGA ISD,NaN,NaN,REGION 07: KILGORE,ANDERSON,District,NaN,No,No,...,NaN,NaN,Earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1902,CAYUGA ISD,1902001.0,CAYUGA H S,REGION 07: KILGORE,ANDERSON,High School,09 - 12,No,No,...,Earned,Earned,Earned,5.0,6.0,8.0,8.0,3.0,3.0,ZONED SCHOOL-TRANSFERS ACCEPTED
2,1902,CAYUGA ISD,1902041.0,CAYUGA MIDDLE,REGION 07: KILGORE,ANDERSON,Middle School,06 - 08,No,No,...,Not Earned,Not Earned,Earned,5.0,6.0,8.0,8.0,3.0,3.0,ZONED SCHOOL-TRANSFERS ACCEPTED
3,1902,CAYUGA ISD,1902103.0,CAYUGA EL,REGION 07: KILGORE,ANDERSON,Elementary,KG - 05,No,No,...,Not Earned,Not Earned,Earned,5.0,6.0,8.0,8.0,3.0,3.0,ZONED SCHOOL-TRANSFERS ACCEPTED
4,1903,ELKHART ISD,NaN,NaN,REGION 07: KILGORE,ANDERSON,District,NaN,No,No,...,NaN,NaN,Not Earned,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dallas_all = data[(data["County"] == "DALLAS") & (data["Charter"] == "No")]

In [27]:
dallas_some = dallas_all[['District',
 'Campus',
 'Region',
 'County',
 'School\nType',
 'Grades\nServed',
 'Number of\nStudents',
 '%\nEconomically\nDisadvantaged',
 '% EB/EL\nStudents',
 'Overall\nScore',
 'Student\nAchievement\nScore',
 'School\nProgress\nScore',
 'Academic\nGrowth\nScore',
 'Relative\nPerformance\nScore',
 'Closing\nthe Gaps Score',
 'Public\nEducation\nGrant',
 'Campus Enrollment\nType']]

In [28]:
dallas_some.head()

,District,Campus,Region,County,School\nType,Grades\nServed,Number of\nStudents,%\nEconomically\nDisadvantaged,% EB/EL\nStudents,Overall\nScore,Student\nAchievement\nScore,School\nProgress\nScore,Academic\nGrowth\nScore,Relative\nPerformance\nScore,Closing\nthe Gaps Score,Public\nEducation\nGrant,Campus Enrollment\nType
2293,CARROLLTON-FARMERS BRANCH ISD,NaN,REGION 10: RICHARDSON,DALLAS,District,NaN,"24,888",63.6%,35.1%,88,85,90,89,90,84,NaN,NaN
2294,CARROLLTON-FARMERS BRANCH ISD,TURNER H S,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,"2,089",67.2%,39.4%,81,82,84,70,84,74,NaN,ZONED SCHOOL-TRANSFERS ACCEPTED
2295,CARROLLTON-FARMERS BRANCH ISD,SMITH H S,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,"2,033",66.6%,32.5%,79,80,81,79,81,74,NaN,ZONED SCHOOL-TRANSFERS ACCEPTED
2296,CARROLLTON-FARMERS BRANCH ISD,GRIMES EDUCATION CENTER,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,65,49.2%,26.2%,82,86,.,.,.,73,NaN,SELECTIVE ENROL SCHL-CRITERIA-BASED
2297,CARROLLTON-FARMERS BRANCH ISD,SALAZAR DISTRICT ALTERNATIVE EDUCATION PROGRAM,REGION 10: RICHARDSON,DALLAS,Elem/Secondary,06 - 12,42,73.8%,31.0%,.,.,.,.,.,.,NaN,SPECIAL ASSIGNMENT SCHOOL

In [36]:
dallas_some["Public\nEducation\nGrant"].unique()

array([nan, 'Yes'], dtype=object)

In [31]:
dallas_hs = dallas_some[dallas_some["Grades\nServed"].str.contains("12", case=False, na=False)]

In [37]:
dallas_hs = dallas_hs.rename(columns={"School\nType": "Type", 
                                      "Number of\nStudents": "Students",
                                     "Grades\nServed": "grades_served",
                                     "%\nEconomically\nDisadvantaged": "perc_ed",
                                     "% EB/EL\nStudents": "perc_eb_el",
                                     "Overall\nScore": "overall_score",
                                     "Student\nAchievement\nScore": "student_ach_score",
                                     "School\nProgress\nScore": "school_prog_score",
                                     "Academic\nGrowth\nScore": "academic_growth_score",
                                     "Relative\nPerformance\nScore": "relative_perf_score",
                                     "Closing\nthe Gaps Score": "closing_gap_score",
                                     "Public\nEducation\nGrant": "Grant",
                                     "Campus Enrollment\nType": "enroll_type"})

In [38]:
dallas_hs.head()

,District,Campus,Region,County,Type,grades_served,Students,perc_ed,perc_eb_el,overall_score,student_ach_score,school_prog_score,academic_growth_score,relative_perf_score,closing_gap_score,Grant,enroll_type
2294,CARROLLTON-FARMERS BRANCH ISD,TURNER H S,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,"2,089",67.2%,39.4%,81,82,84,70,84,74,NaN,ZONED SCHOOL-TRANSFERS ACCEPTED
2295,CARROLLTON-FARMERS BRANCH ISD,SMITH H S,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,"2,033",66.6%,32.5%,79,80,81,79,81,74,NaN,ZONED SCHOOL-TRANSFERS ACCEPTED
2296,CARROLLTON-FARMERS BRANCH ISD,GRIMES EDUCATION CENTER,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,65,49.2%,26.2%,82,86,.,.,.,73,NaN,SELECTIVE ENROL SCHL-CRITERIA-BASED
2297,CARROLLTON-FARMERS BRANCH ISD,SALAZAR DISTRICT ALTERNATIVE EDUCATION PROGRAM,REGION 10: RICHARDSON,DALLAS,Elem/Secondary,06 - 12,42,73.8%,31.0%,.,.,.,.,.,.,NaN,SPECIAL ASSIGNMENT SCHOOL
2298,CARROLLTON-FARMERS BRANCH ISD,CREEKVIEW H S,REGION 10: RICHARDSON,DALLAS,High School,09 - 12,"1,690",53.0%,19.0%,87,88,88,83,88,84,NaN,ZONED SCHOOL-TRANSFERS ACCEPTED